apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-app
  labels:
    app: blue-green
    env: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-green
      env: blue
  template:
    metadata:
      labels:
        app: blue-green
        env: blue
    spec:
      containers:
        - name: web-app
          image: 593927188565.dkr.ecr.us-east-1.amazonaws.com/blue-green-app:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
spec:
  type: LoadBalancer
  selector:
    app: blue-green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
