apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-green
      env: green
  template:
    metadata:
      labels:
        app: blue-green
        env: green
    spec:
      containers:
        - name: web-app
          image: 593927188565.dkr.ecr.us-east-1.amazonaws.com/blue-green-app:v2
          ports:
            - containerPort: 80
