apiVersion: v1
kind: Service
metadata:
  name: blue-green-preview-service # FIXED: Added "-preview"
spec:
  type: LoadBalancer
  selector:
    app: blue-green
    # DO NOT put 'env: blue' here; Argo will inject the selector automatically
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
