apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: blue-green-rollout
  annotations:
    notifications.argoproj.io/subscribe.on-rollout-completed.slack: general
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-green
      env: blue
  template:
    metadata:
      labels:
        app: blue-green
        env: blue
    spec:
      containers:
        - name: web-app
          image: 593927188565.dkr.ecr.us-east-1.amazonaws.com/blue-green-app:v4
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
  strategy:
    blueGreen:
      activeService: blue-green-service
      previewService: blue-green-preview-service
      autoPromotionEnabled: true
      prePromotionAnalysis:
        templates:
          - templateName: success-rate-check
        args: []
        initialDelay: 60s
