apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  template.rollout-status: |
    email:
      subject: Rollout {{.rollout.metadata.name}} is {{.rollout.status.phase}}
    slack:
      attachments:
      - title: "{{.rollout.metadata.name}}"
        timestamp: "{{.time}}"
        color: '{{if eq .rollout.status.phase "Healthy"}}good{{else}}danger{{end}}'
        fields:
        - title: Strategy
          value: "{{.rollout.spec.strategy.type}}"
          short: true
        - title: Phase
          value: "{{.rollout.status.phase}}"
          short: true

  trigger.on-rollout-completed: |
    - when: rollout.status.phase in ['Healthy', 'Degraded']
      send: [rollout-status]

  service.slack: |
    token: $slack-token
