name: Auto-Deploy-Blue-Green

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Push Manifests to EKS
        run: |
          # 1. Connect to your EKS Cluster
          aws eks update-kubeconfig --name blue-green-cluster --region us-east-1

          # 2. Apply the Analysis and Rollout files
          # This will now respect the :v3 tag you manually set!
          kubectl apply -f app/analysis.yaml
          kubectl apply -f app/rollout.yaml

      - name: Verify Argo Rollout Status
        run: |
          # Use the argo rollouts plugin command to see the status properly
          kubectl argo rollouts get rollout blue-green-rollout
